mod 'puppet-nginx', '4.0.0'
mod 'puppetlabs-concat', '7.2.0'
mod 'puppetlabs-stdlib', '8.4.0'
mod 'samuelson-dockeragent', '1.0.0'
mod 'puppetlabs-docker', '5.0.0'
mod 'puppetlabs-apt', '9.0.0'
mod 'puppetlabs-powershell', '5.1.0'
mod 'puppetlabs-pwshlib', '0.10.2'
mod 'puppetlabs-reboot', '4.2.0'
mod 'pltraining/dockeragent'
mod 'puppetlabs/docker'
